In [1]:
import numpy as np
import pandas as pd
from numpy.matlib import repmat

In [2]:
# From the homework

def eigsort(V, eigvals):
    
    # Sort the eigenvalues from largest to smallest. Store the sorted
    # eigenvalues in the column vector lambd.
    lohival = np.sort(eigvals)
    lohiindex = np.argsort(eigvals)
    lambd = np.flip(lohival)
    index = np.flip(lohiindex)
    Dsort = np.diag(lambd)
    
    # Sort eigenvectors to correspond to the ordered eigenvalues. Store sorted
    # eigenvectors as columns of the matrix vsort.
    M = np.size(lambd)
    Vsort = np.zeros((M, M))
    for i in range(M):
        Vsort[:,i] = V[:,index[i]]
    return Vsort, Dsort

In [3]:
def PCA(x):
#     # data set x of shape (N, D) where N is number of observations and D is the number of varaiables or features
#     mean_white = np.mean(x,axis=1)
#     A = x - repmat(mean_white,x.shape[1],1).T
    
    #eigendecomposition
    eigValues, eigVectors = np.linalg.eig(np.dot(x.T,x))
    
    #sort
    V,D = eigsort(eigVectors,eigValues)
    
    return V, D, eigValues

In [4]:
#importing data

red_dataset = pd.read_csv('winequality-red.csv', sep=';')
white_dataset = pd.read_csv('winequality-white.csv', sep=';')

#red & white data merged
wine_data = pd.concat([red_dataset, white_dataset])
wine_dataset = wine_data.iloc[:,:11]
wine_dataset_y = wine_data.iloc[:,11]
wine_dataset_y = wine_dataset_y.to_numpy()

In [5]:
wine_dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
4893     11.2  
4894      9.6  
4895      9.4  
4896     12.8  
4897     11.8  

[6497 rows x 11 columns]

In [6]:
wine_dataset_y

array([5, 5, 5, ..., 6, 7, 6])

In [7]:
from sklearn.preprocessing import StandardScaler
wine_dataset_scaled = StandardScaler().fit_transform(wine_dataset)
wine_dataset_scaled

array([[ 0.14247327,  2.18883292, -2.19283252, ...,  1.81308951,
         0.19309677, -0.91546416],
       [ 0.45103572,  3.28223494, -2.19283252, ..., -0.11507303,
         0.99957862, -0.58006813],
       [ 0.45103572,  2.55330026, -1.91755268, ...,  0.25811972,
         0.79795816, -0.58006813],
       ...,
       [-0.55179227, -0.6054167 , -0.88525328, ..., -1.42124765,
        -0.47897144, -0.91546416],
       [-1.32319841, -0.30169391, -0.12823371, ...,  0.75571005,
        -1.016626  ,  1.9354021 ],
       [-0.93749534, -0.78765037,  0.42232597, ...,  0.25811972,
        -1.41986693,  1.09691202]])

In [8]:
eigenvecs, eigenvalsMatrix, eigenvals = PCA(wine_dataset_scaled)

In [9]:
test1 = wine_dataset_scaled.dot(eigenvecs.T[0])
test2 = wine_dataset_scaled.dot(eigenvecs.T[1])
#test3 = wine_dataset_scaled.dot(eigenvecs.T[2])
#test4 = wine_dataset_scaled.dot(eigenvecs.T[3])

In [10]:
testCombined = pd.DataFrame(test1, columns=['PC1'])
testCombined['PC2'] = test2
testCombined['Quality'] = wine_dataset_y
#testCombined['PC3'] = test3
#testCombined['PC4'] = test4
pd.DataFrame(testCombined).to_csv('2_PCA.csv')
testCombined

PC1       PC2  Quality
0     3.205996  0.416523        5
1     3.039051  1.107462        5
2     3.071893  0.878964        5
3     1.571262  2.112545        6
4     3.205996  0.416523        5
...        ...       ...      ...
6492  0.062824 -1.934205        6
6493 -1.866989  0.524431        5
6494 -0.571133 -0.722662        6
6495 -0.090052 -3.545780        7
6496 -0.512576 -2.891040        6

[6497 rows x 3 columns]

In [11]:
# Comparison to 
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
principalComponents = pca.fit_transform(wine_dataset_scaled)
principalDf = pd.DataFrame(principalComponents)

In [12]:
principalDf

0         1         2         3
0    -3.205996  0.416523 -2.722237 -0.796778
1    -3.039051  1.107462 -2.046952 -0.770225
2    -3.071893  0.878964 -1.742580 -0.802257
3    -1.571262  2.112545  2.592917 -0.292785
4    -3.205996  0.416523 -2.722237 -0.796778
...        ...       ...       ...       ...
6492 -0.062824 -1.934205  0.223912  0.189443
6493  1.866989  0.524431 -0.431798  0.183000
6494  0.571133 -0.722662  0.091469 -0.939670
6495  0.090052 -3.545780  0.141195 -0.055725
6496  0.512576 -2.891040  0.739417 -0.449185

[6497 rows x 4 columns]

In [13]:
pca.explained_variance_ratio_

array([0.2754426 , 0.22671146, 0.14148609, 0.08823201])